#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

set -x
set -e -o pipefail

# This test case is to test Java Evaluation works with the same setup of users.
# The eval test uses some pretrained models which are not part of the CNTK repository itself
# We use the dataset from an external location specified using an environment variable
if [[ -z "$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY" || ! -d "$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY" ]]; then
  echo This test uses external data that is not part of the CNTK repository. Environment variable CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY must be set to point to the external test data location.
  exit 1
fi

 # Copy pretrained models and data
TestDataDir=`cygpath -au $CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY/Bindings/Java`
LocalDataDir="$TEST_ROOT_DIR/../../bindings/java/JavaEvalTest/data"
if [ ! -d "$LocalDataDir" ]; then
  mkdir $LocalDataDir
fi
cp $TestDataDir/* $LocalDataDir


if [ "$OS" == "Windows_NT" ]; then
  # Run the evaluation test
  CntkRoot=`cygpath -aw $TEST_ROOT_DIR/../..`
  DllDir=`cygpath -aw $TEST_BIN_DIR` 

  cd $TEST_BIN_DIR
  "$CntkRoot/bindings/java/JavaEvalTest/run-java-test.cmd" $CntkRoot $DllDir

else
  # Run the evaluation test
  CntkRoot=$TEST_ROOT_DIR/../..
  
  cd $TEST_BIN_DIR
  $CntkRoot/bindings/java/JavaEvalTest/run-java-test.bash $CntkRoot $TEST_BUILD_LOCATION/$TEST_FLAVOR/lib

fi
